/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 canva.glb -T 
Files: canva.glb [5.81MB] > /Users/hsuwinlat/Desktop/jsm pj/r3f-setup/public/canva-transformed.glb [513.75KB] (91%)
Author: DailyArt (https://sketchfab.com/D.art)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/canvas-shoe-38a0936e511b4f7896edf9cc2c5f198d
Title: canvas shoe
*/

import React, { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { Color } from "three";

export function Canva(props) {
  const { nodes, materials } = useGLTF("/canva-transformed.glb");

  useEffect(() => {
    Object.entries(materials).map((item) => {
      item[1].color = new Color(`${props.color}`);
    });
  }, [props.color]);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.initialShadingGroup}
        position={[7.43, 74.494, -0.273]}
        scale={173.895}
      />
    </group>
  );
}

useGLTF.preload("/canva-transformed.glb");
