/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 white-nike.glb -T 
Files: white-nike.glb [34.65MB] > /Users/hsuwinlat/Desktop/jsm pj/r3f-setup/public/white-nike-transformed.glb [2.98MB] (91%)
Author: les83machines (https://sketchfab.com/les83machines)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-flex-runner-409eb9377a454fdba2ed6e45803966eb
Title: NIKE FLEX RUNNER
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Color } from "three";

export function WhiteNike(props) {
  const { nodes, materials } = useGLTF("/white-nike-transformed.glb");
  useEffect(() => {
    Object.entries(materials).map((item) => {
      item[1].color = new Color(`${props.color}`);
    });
  }, [props.color]);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.model_tex_u1_v1_0.geometry}
        material={materials.tex_u1_v1}
      />
    </group>
  );
}

useGLTF.preload("/white-nike-transformed.glb");
